image: dev/java
  
cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - build/build-pipeline/node_modules/

before_script:
  - cd build/build-pipeline; npm install

after_script:
  - cd ../..

stages:
  - build
  - test
  - report  

build:
  stage: build
  tags:
    - cmis
  script:
    - echo "before copy Props.java"
    - echo "in build-pipeline path"
    - ls -lh /builds/cmis/cmis-server/build/build-pipeline/
    - cat /builds/cmis/cmis-server/build/build-pipeline/Props.java
    - cat /builds/cmis/cmis-server/build/build-pipeline/redisson.json    
    - echo "in source path"
    - ls -lh /builds/cmis/cmis-server/cmis-tests/src/test/java/com/pogeyan/cmis/mongo/tests/
    - cat /builds/cmis/cmis-server/cmis-tests/src/test/java/com/pogeyan/cmis/mongo/tests/Props.java
    - echo "before copy redisson.json"
    - ls -lh /builds/cmis/cmis-server/server/src/main/resources/
    - cat /builds/cmis/cmis-server/server/src/main/resources/redisson.json
    - gulp build
    - echo "after copy Props.java"
    - ls -lh /builds/cmis/cmis-server/cmis-tests/src/test/java/com/pogeyan/cmis/mongo/tests/
    - cat /builds/cmis/cmis-server/cmis-tests/src/test/java/com/pogeyan/cmis/mongo/tests/Props.java
    - echo "after copy redisson.json"
    - ls -lh /builds/cmis/cmis-server/server/src/main/resources/
    - cat /builds/cmis/cmis-server/server/src/main/resources/redisson.json
  artifacts:
    paths:
    - cmis-tests/target
    - server/target
    - ldap/target
    - core/target
    - data/target
    - graphQL/target
    expire_in: 5 days
  only:
    - v1.0  
    
test:
  stage: test
  tags:
    - cmis
  dependencies:
    - build
  script:
    - echo "before copy Props.java"
    - echo "in build-pipeline path"
    - ls -lh /builds/cmis/cmis-server/build/build-pipeline/
    - cat /builds/cmis/cmis-server/build/build-pipeline/Props.java
    - cat /builds/cmis/cmis-server/build/build-pipeline/redisson.json    
    - echo "in source path"
    - ls -lh /builds/cmis/cmis-server/cmis-tests/src/test/java/com/pogeyan/cmis/mongo/tests/
    - cat /builds/cmis/cmis-server/cmis-tests/src/test/java/com/pogeyan/cmis/mongo/tests/Props.java
    - echo "before copy redisson.json"
    - ls -lh /builds/cmis/cmis-server/server/src/main/resources/
    - cat /builds/cmis/cmis-server/server/src/main/resources/redisson.json
    - gulp test
    - echo "after copy Props.java"
    - ls -lh /builds/cmis/cmis-server/cmis-tests/src/test/java/com/pogeyan/cmis/mongo/tests/
    - cat /builds/cmis/cmis-server/cmis-tests/src/test/java/com/pogeyan/cmis/mongo/tests/Props.java
    - echo "after copy redisson.json"
    - ls -lh /builds/cmis/cmis-server/server/src/main/resources/
    - cat /builds/cmis/cmis-server/server/src/main/resources/redisson.json
  artifacts:
    paths:
    - server/target
    - ldap/target
    - core/target
    - data/target
    - graphQL/target
    - target
    expire_in: 5 days
  only:
    - v1.0

report:
  stage: report
  tags:
    - cmis
  dependencies:
    - build
    - test
  script:
    - gulp reports
  only:
    - v1.0